creation_rules:
    - age: >-
          age1cjz0m2f8sqpm89xemq0pdhx5twv8lqe5htvmwtm4arp942rnrfjsfznz8k,
          age1dhdrjkdxl5gssyy0kzx9desfztwd7kxd3pp8hmscate7nj9nu9lsrlvxrj,
          age12qmv9pl9dkxslgz7a7zu9uja3yhflnjkdxrk2vu0687t5smdfeus2tvzk3
